# Generated by Django 5.0.6 on 2024-07-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chat_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="image",
        ),
    ]
